# Generated by Django 5.0.3 on 2024-04-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism_app', '0004_alter_reservation_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
